### ISSUE TITLE
Cannot resolve module HTTP

### ISSUE THREAD

**Issue by muhibbudins** [syumai/dinatra#13]
Hi @syumai,

I think this import url is doesn't exist, the http.ts is move to sub directory **http**.

https://github.com/syumai/dinatra/blob/b1636562e9c61849393b5ab283fc1cb677e9ddd0/mod.ts#L1

See this repo https://github.com/denoland/deno_std/tree/master/http

Thank you

**Comment by muhibbudins** [comment]
Anyway, i get an error when i start dinarta using deno.

```bash
Deno requests network access to "listen". Grant? [yN] y
listening on http://0.0.0.0:8080/
Error: assert
    at assert (deno/js/util.ts:25:11)
    at getTime (deno/js/timers.ts:37:3)
    at fireTimers$1 (deno/js/timers.ts:135:15)
    at handleAsyncMsgFromRust (deno/js/dispatch.ts:35:3)
```

Do you have solution about this? Thanks

**Comment by syumai** [comment]
@muhibbudins 
Thank you for your PR! I've merged #14.

About another problem, I've never seen that error message.
Please tell me about your environment :pray: 

My environment:
OS: Ubuntu 18.04
deno: 0.2.6

This code works fine in my env.
```ts
import {
  app,
  get,
} from 'https://denopkg.com/syumai/dinatra/mod.ts';

app(
  get('/hello', () => 'hello')
);
```

**Comment by muhibbudins** [comment]
@syumai 

Forget it, after update to 0.2.6 a example works like a charm. 😬 

Thank you 👍

**Comment by syumai** [comment]
That's good! I'll close this issue.
