### ISSUE TITLE
Leaking tests

### ISSUE THREAD

**Issue by olaven** [syumai/dinatra#57]
Hi! Thanks for this project! I have played around with it quite a bit today, and I think it's neat 😄 
I have come across something that _might_ be a bug. 
It may also be incompitence on my part. 
In any case: 

I have written a small API, and I want to unit test it. I have come up with this: 
```ts
const with_server = (action: (port: number) => any) => async () => {

    const port = Math.floor(Math.random() * (9000 - 1000 + 1)) + 1000;
    const app = new App(port); 
    
    app.serve(); 
    action(port); 
    await app.close();
} 

Deno.test("Can fetch server in test", with_server(async port => {

    const response = await fetch(`http://localhost:${port}/endpoint`);
    assertEquals(200, response.status);
}));
```

However, something about the way the server closes down does not seem to work as expected: 
Running `deno test --allow-net app_test.ts`: 
```

Can fetch server in test
Error: Test case is leaking async ops.
Before:
  - dispatched: 0
  - completed: 0
After:
  - dispatched: 3
  - completed: 2
    at Object.assert ($deno$/util.ts:25:11)
    at asyncOpSanitizer ($deno$/testing.ts:46:5)
    at async Object.resourceSanitizer [as fn] ($deno$/testing.ts:67:5)
    at async TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:259:11)
    at async Object.runTests ($deno$/testing.ts:341:20)

failures:

	Can fetch server in test
```

Does it look familiar? 

Thanks, and have a nice day!
olaven

**Comment by syumai** [comment]
I'll check this later, thanks!

**Comment by olaven** [comment]
Further discoveries: 
The test setup works fine with `v0.36.0` of Deno, but not later. 
My guess would be that it is related to some of these changes:  
- fix(std/http): Close open connections on server close (#3679)
- fix(std/http): Properly await ops in a server test (#4436)
- refactor: Improve test runner (#4336, #4352, #4356, #4371)

 (from [releases](https://github.com/denoland/deno/blob/master/Releases.md))

**Comment by olaven** [comment]
Seems like something in Deno-fetch's resolving of the body is causing the issue.
In other words, the error may not be reated to Dinatra. 
Awaiting the body, e.g. `await response.text()` is a workaround that makes this issue go away. 

```ts 
Deno.test("Can fetch server in test", with_server(async port => {

    const response = await fetch(`http://localhost:${port}/endpoint`);
    await response.text();
    assertEquals(200, response.status);
}));
```

**Comment by olaven** [comment]
I am closing this issue, as it appears to not be related to Diantra. 
I posted an issue about it [here](https://github.com/denoland/deno/issues/4735).

Sorry about that. Thanks for your time!
